[workspace]
members = [
    "examples/*",
    "rosalina",
]

[workspace.dependencies]
rosalina = { path = "rosalina" }

[profile.dev]
panic = "abort"

[profile.release]
opt-level = "s"
panic = "abort"
