[package]
name = "cargo-luma"
version = "0.1.0"
license = "ISC OR Apache-2.0"
edition = "2021"

[dependencies]
anyhow = "1.0.67"
cargo_metadata = "0.15.0"
clap = { version = "4.0", features = ["derive"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
