[alias]
# https://internals.rust-lang.org/t/problems-of-cargo-config-files-and-possible-solutions/12987
luma = "run --profile host-release --target x86_64-pc-windows-msvc -p cargo-luma -- luma"

[build]
target = "powerpc-nintendo-wii-freestanding.json"

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins", "alloc", "std"]
